version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Debug
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build_script:
- ps: dotnet build ./CodeJam.Light.sln