version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Debug
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
environment:
  APPVEYOR_RDP_PASSWORD: test-me-123!
build_script:
- ps: dotnet build .\CodeJam.Light.sln -p:Version=$env:APPVEYOR_BUILD_VERSION
test: off #disable auto-tests
test_script:
  - ps: .\pipelines\appveyor.tests.ps1
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))